### ISSUE TITLE
nixpkgs generated vim plugins compatibility

### ISSUE THREAD

**Issue by maksar** [Shados/envy#1]
Since pkgs removed overrides parameter from https://github.com/NixOS/nixpkgs/commit/f269c57097d4b2b56556d5393d8248659dc40fc3#diff-b7a49d194ede1147f14a19a5be0875f0a7d9807db98d49602ec270e5ae44395cL2 envy it not capable to work in home-manager mode ;(

I would like to help with resolving the issue (since I am using envy myself), but don't have time right now. So, just reporting the issue here not to forget.

```
darwin-rebuild switch
building the system configuration...
error: anonymous function at /nix/store/apzjwxc0d7bsllfk317ix7sy67zr946h-nixpkgs/pkgs/misc/vim-plugins/generated.nix:2:1 called with unexpected argument 'overrides'

       at /nix/store/8wvz01vvrhmrg2282dlw7kyqz210lkfj-nixpkgs-21.05pre290801.7013a0f2791/nixpkgs/lib/customisation.nix:69:16:

           68|     let
           69|       result = f origArgs;
             |                ^
           70|
(use '--show-trace' to show detailed location information)
```

**Comment by Shados** [comment]
Oh, thanks for the heads-up. I'll probably have some free time to look into this over the weekend, if you don't get to it before that.

**Comment by maksar** [comment]
Issue seems to be around here: https://github.com/Shados/envy/blob/master/module.nix#L1000

**Comment by maksar** [comment]
Specifying `baseVimPlugins = pkgs.vimPlugins;` helps a little, but due to `filterVimPlugins = attrs: filterAttrs (n: v: isDerivation v) attrs;` it brakes on deprecations.json from nixpkgs.

```
building the system configuration...
error: gist-vim was renamed to vim-gist on 2020-03-27. Please update to vim-gist.
```

Again, no worries, issue is fixable locally (by filtering out deprecated plugins from vimPlugins attrset, for example). Time is the most valuable resource and I don't ask for a fix, just letting you know about my path ;)

**Comment by maksar** [comment]
Last comment for today – was able to make everything work with:
```
    baseVimPlugins = (pkgs.lib.filterAttrs (k: v:
      !(builtins.elem k (pkgs.lib.attrNames (builtins.fromJSON
        (builtins.readFile
          (pkgs.path + "/pkgs/misc/vim-plugins/deprecated.json"))))))
      pkgs.vimPlugins);
```

I'm not sure what to think about the idea to `throw` on attribute access, not so experienced with nixpkgs development...

**Comment by Shados** [comment]
> it brakes on deprecations.json from nixpkgs

Yeah, that's why I wasn't directly using `pkgs.vimPlugins` -- I [had been previously](https://github.com/Shados/envy/commit/e3401c93086e1cf6e1352f692aafb3d625a12986). 

-----

> I'm not sure what to think about the idea to `throw` on attribute access, not so experienced with nixpkgs development...

I'm not a fan of it either, but nixpkgs doesn't have a package-level equivalent to the NixOS module assertion system, so this is what we get.

Anyway, your solution works and is a bit less hacky than my previous approach, so I'll go with it.
