### ISSUE TITLE
onedark-nvim problem

### ISSUE THREAD

**Issue by maksar** [Shados/envy#2]
Somehow Nixpkgs has a nonsense situation currently, they have `onedark-nvim` in both https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vim-plugins/aliases.nix (aliased to `onedarkpro-nvim`) and https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vim-plugins/generated.nix files, which (I believe) should not happen.

Locally overriding `baseVimPlugins` to exclude `k != "onedark-nvim"` from list of plugins – helps.

Just letting you know about the issue, don't have time to come up with a proper fix to detect such situation...

**Comment by Shados** [comment]
Yeah, there's a nixpkgs PR for the alias issue [here](https://github.com/NixOS/nixpkgs/pull/154554). I have an envy change that works around this kind of issue, but it changes some semantics in ways I'm not entirely happy with. I'll consider further options if it happens again in future, though.
