### ISSUE TITLE
Usage of the rtp attribute doesn't guarantee that corresponding directory exists

### ISSUE THREAD

**Issue by maksar** [Shados/envy#3]
Looks like this this PR https://github.com/NixOS/nixpkgs/pull/171064/files Nixpkgs changed the way `rtp` attribute is added to the vim plugin derivation. Or maybe it is related to the latest nix daemon per se. But envy now fails to read the plugin dir (while Lua init procedure) because it doesn't exist.
```
dirSet = builtins.readDir path;
```

This happens because accessing `rtp` doesn't actually trigger a plugin deviation to be built.

**Comment by maksar** [comment]
I tried to overcome the issue locally by replacing `plugin.rtp` with `(builtins.seq (builtins.storePath plugin.outPath) plugin.rtp)`. But since I'm using flakes, this will not work...

**Comment by Shados** [comment]
I looked into this a bit at the time, but couldn't reproduce the issue on my system, not sure why. Shouldn't be relevant since 17e7d47c98b0e17dafd530c385147db44a530424 however -- if `.outPath` references don't result in derivations being built on your system, you should have much bigger problems...
